export const QUIZZES_LOAD = 'QUIZZES_LOAD'
export const QUIZZES_LOAD_SUCCESS = 'QUIZZES_LOAD_SUCCESS';
export const QUIZZES_LOAD_ERROR = 'QUIZZES_LOAD_ERROR';

export const GET_QUIZ = 'GET_QUIZ';
export const GET_QUIZ_ERROR = 'GET_QUIZ_ERROR';
export const GET_QUIZ_SUCCESS = 'GET_QUIZ_SUCCESS';

export const CREATE_QUIZ_UPDATE = 'CREATE_QUIZ_UPDATE';
export const CREATE_QUIZ_SUBMIT = 'CREATE_QUIZ_SUBMIT';
export const CREATE_QUIZ_SUBMIT_ERROR = 'CREATE_QUIZ_SUBMIT_ERROR';
export const CREATE_QUIZ_SUBMIT_SUCCESS = 'CREATE_QUIZ_SUBMIT_SUCCESS';

export const UPDATE_QUIZ_SUBMIT = 'UPDATE_QUIZ_SUBMIT';
export const UPDATE_QUIZ_SUBMIT_ERROR = 'UPDATE_QUIZ_SUBMIT_ERROR';
export const UPDATE_QUIZ_SUBMIT_SUCCESS = 'UPDATE_QUIZ_SUBMIT_SUCCESS';

export const DELETE_QUIZ = 'DELETE_QUIZ';
export const DELETE_QUIZ_ERROR = 'DELETE_QUIZ_ERROR';
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS';

export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_ERROR = 'GET_ALL_QUESTIONS_ERROR';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';

export const NAVIGATE = 'NAVIGATE';
export const NAVIGATE_SUCCESS = 'NAVIGATE_SUCCESS';
